### ISSUE TITLE
module vs standalone setup errors

### ISSUE THREAD

**Issue by ShiftyMcCool** [dappsnation/ng-rive#50]
I'm using v0.3.0 with a standalone component and getting errors while navigating.

If I set up my component with `RiveCanvas` and `RiveLinearAnimation` in the imports, it doesn't run the animation and I get the following error:
```
main.ts:6 ERROR NullInjectorError: R3InjectorError(AppModule)[RiveService -> RiveService]: 
  NullInjectorError: No provider for RiveService!
    at NullInjector.get (core.mjs:8771:27)
    at R3Injector.get (core.mjs:9200:33)
    at R3Injector.get (core.mjs:9200:33)
    at ChainedInjector.get (core.mjs:13007:36)
    at lookupTokenUsingModuleInjector (core.mjs:4436:39)
    at getOrCreateInjectable (core.mjs:4484:12)
    at Module.ɵɵdirectiveInject (core.mjs:10778:12)
    at NodeInjectorFactory._class2_Factory [as factory] (ng-rive.mjs:80:84)
    at getNodeInjectable (core.mjs:4669:44)
    at instantiateAllDirectives (core.mjs:11598:27)
 ```

If I use `RiveModule` instead, the animation runs but I also get this error:
```
ERROR BindingError: LinearAnimationInstance instance already deleted
    at Q (canvas_advanced.mjs:39:301)
    at Hb (canvas_advanced.mjs:47:153)
    at Ib.delete (canvas_advanced.mjs:71:45)
    at ng-rive.mjs:806:47
    at timer (zone.js:2367:41)
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:25990:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:25990:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Object.onInvokeTask (core.mjs:26300:33)
```
Not sure what I'm doing wrong, it's not that complex of a setup. Here's some of the code, I'm just intercepting HTTP requests and using a service to display the animation component:

loader.interceptor.ts:
```
@Injectable()
export class LoaderInterceptor implements HttpInterceptor {
  constructor(private loader: FullScreenLoaderService) {}
  public intercept(
    req: HttpRequest<any>,
    next: HttpHandler,
  ): Observable<HttpEvent<any>> {
    this.loader.showLoader()
    return next.handle(req).pipe(finalize(() => this.loader.hideLoader()))
  }
}
```

full-screen-loader.service.ts:
```
@Injectable({
  providedIn: 'root',
})
export class FullScreenLoaderService {
  private apiCount = 0
  private isLoadingSubject = new BehaviorSubject<boolean>(false)
  public isLoading$ = this.isLoadingSubject.asObservable()

  public showLoader(): void {
    if (this.apiCount === 0) {
      this.isLoadingSubject.next(true)
    }
    this.apiCount++
  }

  public hideLoader(): void {
    this.apiCount--
    if (this.apiCount === 0) {
      this.isLoadingSubject.next(false)
    }
  }
}
```

full-screen-loader.component.ts:
```
@Component({
  selector: 'app-full-screen-loader',
  standalone: true,
  imports: [CommonModule, RiveModule], // OR  [CommonModule, RiveCanvas, RiveLinearAnimation],
  templateUrl: './full-screen-loader.component.html',
  styleUrls: ['./full-screen-loader.component.scss'],
})
export class FullScreenLoaderComponent {
  constructor(public loader: FullScreenLoaderService) {}
}
```

full-screen-loader.component.html:
```
<div
  *ngIf="loader.isLoading$ | async"
  class="w-full h-full fixed block top-0 left-0 bg-white opacity-90 z-50"
>
  <div
    class="w-full h-full bg-white opacity-75 z-50 flex justify-center items-center"
  >
    <app-loader-animation></app-loader-animation>
  </div>
</div>
```

Any ideas?

**Comment by GrandSchtroumpf** [comment]
Can you try version 3.0.1 ?
Else try to add `importProvidersFrom(RiveModule)` in the `providers` field of the `bootstrapApplication`

**Comment by ShiftyMcCool** [comment]
@GrandSchtroumpf Thanks for the reply! I've upgraded to v0.3.1 (I assume this is what you meant) which had no effect. My `AppComponent` isn't standalone but everything else is, so I'm not calling `bootstrapApplication`.  Just for the heck of it, I tried using `importProvidersFrom(RiveModule)` to the providers of my `AppModule` but going down that road caused too many other errors to deal with. Any other suggestions?

**Comment by GrandSchtroumpf** [comment]
@ShiftyMcCool From what I understand, the `RiveService` is not provided. Since version 0.3.1 it's `providedIn: 'root'` so it should not happen. Historically the `RiveService` was provided by the `RiveModule`. 
You can try to add `RiveService` in the `providers` list of your `FullScreenLoaderComponent` maybe.

**Comment by ShiftyMcCool** [comment]
@GrandSchtroumpf the last time I tried, i was still using `RiveModule` in my standalone component. I switched to using the documented `RiveCanvas, RiveLinearAnimation` setup and the animation works this time with 0.3.1 but I'm still seeing the following error in the console:
`ERROR BindingError: LinearAnimationInstance instance already deleted`

**Comment by GrandSchtroumpf** [comment]
@ShiftyMcCool Ok, at least it's not a RiveService issue. Are you using `@rive-app/canvas-advanced` version 2.4.0 ?

**Comment by ShiftyMcCool** [comment]
@GrandSchtroumpf According to the documentation, it comes in the package so I haven't installed it myself.  Looking in the package-lock.json shows me that `@rive-app/canvas-advanced` 2.4.0 is, indeed, installed

**Comment by GrandSchtroumpf** [comment]
Could you open a stackblitz with minimal reproduction ? It would be easier for me to provide feedback

**Comment by ShiftyMcCool** [comment]
Sorry for the delay, I haven't had much time for this lately.  I will provide a stackblitz as soon as I can.  Thanks!
